version: '3.7'

services:
  dind:
    image: docker:dind
    privileged: true
    volumes:
      - docker-volume:/var/lib/docker

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://dind:2375
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - dind

volumes:
  docker-volume:
  jenkins_home:

